# Generated by Django 2.0.6 on 2018-06-12 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
        ('core', '0002_auto_20180606_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='documento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.Documento'),
        ),
    ]
